services:
  frontend:
    image: node:20
    working_dir: /app/frontend
    volumes:
      - "volume1:/app"
    command: [ "npm", "run", "dev", "--host" ]
    ports:
      - "5173:5173"

  backend:
    image: node:20
    working_dir: /app/backend
    volumes:
      - "volume1:/app"
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  install:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: [ "sh", "-c", "npm install -g concurrently nodemon && cd frontend && npm install && cd ../backend && npm install" ]
    depends_on:
      - frontend
      - backend

volumes:
    "volume1":
